language: node_js
node_js:
  - 12

jobs:
  include:
    - stage: test
      script: yarn run test
    - stage: coverage
      script: ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info && rm -rf ./coverage
