language: node_js
node_js:
  - 12

jobs:
  include:
    - stage: test and coverage
      script: yarn run test && sed -i "s/\.\.\/\.\.\///g" coverage/lcov.info && ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info && rm -rf ./coverage

deploy:
  provider: script
  script: echo "DEPLOY"
  on:
    tags: true