language: node_js
node_js:
  - 12

jobs:
  include:
    - stage: test and coverage
      script: yarn run test && sed -i "s/\.\.\/\.\.\///g" coverage/lcov.info && ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info && rm -rf ./coverage

deploy:
  provider: script
  script: sed -i "s/TRAVIS_TAG/$TRAVIS_TAG/g" package.json && yarn run build && npm publish ./dist
  on:
    tags: true